INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua A', 'SP', 'SP', '253', '11703558', 'sem complemento', 'tupi');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood)  VALUES ('Rua Bororos', 'PG', 'SP', '253', '11703559', 'sem complemento', 'tupi');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua Dorivadlo Francisco Loria', 'PG', 'SP', '258', '11720320', 'sem complemento', 'mirim');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua Fradique Coutinho', 'SP', 'SP', '618', '05416000', 'apto 13', 'Pinheiros');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua Atararis', 'SP', 'SP', '88', '02545333', 'sem complemento', 'jaguare');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua 12345678', 'SP', 'SP', '88', '12345678', 'sem complemento', 'jaguare');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua 11114444', 'SP', 'SP', '88', '11114444', 'sem complemento', 'jaguare');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua 55556666', 'SP', 'SP', '88', '55556666', 'sem complemento', 'jaguare');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua 55550000', 'SP', 'SP', '88', '55550000', 'sem complemento', 'jaguare');
INSERT INTO address (street, city, state, address_number, zip_code, address_detail, neighborhood) VALUES ('Rua 77770000', 'SP', 'SP', '88', '77770000', 'sem complemento', 'jaguare');
